### PR TITLE
Added check on modification time to avoid regenerating all files.

### PR DESCRIPTION
**Pull request by steingod**
This is an attempt to address #43 . It is tested on data at thredds.met.no where we have access to the underlying file system as well. It would be good with some independent test before merge.

### CODE REVIEW

**Comment by ferrighi** [comment]
This is a very good feature to have. I've tested a bit and I have 2 comments:

1. This will fail if ds.modified is not available or not the right format (e.g. niva catalogue -not available- and geus - time data '2024-11-24T16:07:54.896Z' does not match format '%Y-%m-%dT%H:%M:%SZ')
2. How do we force regenerating MMDs? I think we need to be able to do that when we make changes in the harvester to improve metadata extraction. Now MMDs will be regenerated only if the underlying file is changed, so update of the software will never be applied to old records.

**Comment by ferrighi** [comment]
Yes, I agree.

**Comment by steingod** [comment]
Can you check again? I have tested on our, NIVA and GEUS servers now.

**Comment by ferrighi** [comment]
It's good. I've tested a couple of  internal endpoints, with and without flag. External as well.

**Pull request merged**
